[supervisord]
nodaemon=true
environment=WINEDLLOVERRIDES="mscoree,mshtml="

[program:mt5]
command=/usr/bin/wine "/config/.wine/drive_c/Program Files/MetaTrader 5/terminal64.exe"
environment=DISPLAY=":0",WINEPREFIX="/config/.wine",WINEDEBUG="-all",WINEDLLOVERRIDES="mscoree,mshtml="
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
